import os
import sys
import subprocess

VERSION_PY = os.path.join(os.path.dirname(__file__), 'version.py')

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


def version_setter():
    try:
        version_git = subprocess.check_output(["git", "describe", "--tags"]).rstrip().decode("utf-8")
        return version_git
    except:
        with open(VERSION_PY, 'r') as f:
            version_git = f.read().strip().split('=')[-1].replace('"', '')
            return version_git


MESSAGE = "# Do not edit this file. " \
          "# Pipeline versioning is governed by git tags."


def version_writer():
    with open(VERSION_PY, 'w') as f:
        f.write(MESSAGE + os.linesep + "__version__ = '{ver}'".format(ver=version_setter()) + '\n')


def windows_packages_only(*args):
    packages = [a for a in args]
    return packages if sys.platform == 'win32' else []


setup(name='InQRy',
      version="{ver}".format(ver=version_git),
      license='MIT',
      description='Gets machine specs and generates a QR code containing them',
      author='Eric Hanko',
      author_email='v-erhank@microsoft.com',
      packages=['inqry', "inqry.system_specs"],
      long_description=open('README.md').read(),
      install_requires=["pytest-runner", "pytest", "qrcode", "PyYAML", "Pillow"] + windows_packages_only("pypiwin32",
                                                                                                         "wmi"),
      setup_requires=['pytest-runner'],
      tests_require=['pytest'],
      )
